name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

  all-tests-pass:
    runs-on: ubuntu-20.04
    needs: build-lint-test
    steps:
      - run: echo "Great success"
